[package]
name = "backend-embedded-graphics"
version = "0.1.0"
authors = ["Dániel Buga <bugadani@gmail.com>"]
edition = "2018"

[dependencies]
embedded-graphics = "0.7.0-beta.1"
embedded-text = { git = "https://github.com/embedded-graphics/embedded-text" }
embedded-gui = { path = ".." }
